# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f94de51c238c5db28aeb4e9b1b173e8ac2b71272fd7e84db794832ca809b560450ea98306f78a3f57f9865244a3d33457b7ad05e505da4cb79a94bcc32cce93f

test:
  secret_key_base: 9463c025554cab138d35afe1986775e0e6acc4a0334ada25c825055557dfd6b047fd4ff952a4246a26a622081b3f643dc032e815435b9ee60817ce6e439eec8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
